FROM python:3.9

RUN apt-get update -y && apt-get install -y nano
RUN pip install xarray pymongo netCDF4

WORKDIR /app
COPY proofread.py .
COPY proofread.sh .
RUN chown -R 1000660000 /app
CMD bash proofread.sh